### ISSUE TITLE
Reference Doc?

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICMadness-2018#19]
@joeyklee, should we add a link to and/or any explanation about your reference guide (https://gist.github.com/joeyklee/313256314f0284c45b01b5d54923e683) to the README here?

**Comment by joeyklee** [comment]
Hi @shiffman ! I'm fine with either referencing that existing reference guide or adding a version of it directly to the readme. I will prepare something maybe more ITP related and make a PR so we can incorporate it if that makes sense.

**Comment by shiffman** [comment]
@joeyklee sounds like a perfect plan to me!

**Comment by shiffman** [comment]
Thanks for #28 @joeyklee!
