### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICMadness-2018#7]
Generate a permalink (with random nunmber seed?) to reproduce the spin.

**Comment by shiffman** [comment]
Working on this feature now!

**Comment by shiffman** [comment]
@mithru can you check if the permalink is accessible? (Looks like at a minimum it needs a color contrast fix).

https://itpnyu.github.io/ICMadness-2018/spin/?topic=9&action=14&tech=7

**Comment by shiffman** [comment]
Adding a note here that the speed of the spin could be played with (I might have it spin round and round 1 or 2 times before slowing down in order to increase the drama.)

**Comment by mithru** [comment]
Looking into this now.

**Comment by shiffman** [comment]
Thanks @mithru! #12 is probably higher priority if you looking at the code. I'll be available to add any last features or fix things later tonight or tomorrow morning beforehand.

**Comment by shiffman** [comment]
The spinning seems great now so closing! Can always revisit later...
